engines:
  credo:
    enabled: true
    channel: "beta"
    checks:
      module_doc:
        enabled: false
      max_line_length:
        enabled: false
      alias_usage:
        enabled: false
ratings:
  paths:
  - "**.ex"
  - "**.exs"
